/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VentanaTienda extends javax.swing.JFrame {
int total = 0;

        ImageIcon imag = new ImageIcon("src\\casino\\img\\fondoBack4.jpg");
    
        Image im = imag.getImage(); // Transforma el ImageIcon a Image
        Image back = im.getScaledInstance(525, 325, java.awt.Image.SCALE_SMOOTH); // Escala la imagen
        ImageIcon f1 = new ImageIcon(back);     
      

    /**
     * Creates new form VentanaTienda
     */
    public VentanaTienda() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        lblImg.setIcon(f1);
        lblCred.setText("Creditos: " + Integer.toString(Program.creditos));
//        this.setSize(403, 300); // Ponemos el tamaño de la ventanaJuego en 800x400
             this.setLocationRelativeTo(this); // Hacemos que la ventana quede en el medio
             this.setTitle("Tienda"); // Le ponemos el nombre "Tragamonedas" a la ventana
             this.setResizable(false); // Hacemos que no se pueda Maximar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFood = new javax.swing.JButton();
        btnDrink = new javax.swing.JButton();
        btnCar = new javax.swing.JButton();
        btnTravel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        list1 = new java.awt.List();
        lblTotal = new javax.swing.JLabel();
        lblCred = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        list2 = new java.awt.List();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFood.setBackground(new java.awt.Color(51, 51, 51));
        btnFood.setForeground(new java.awt.Color(204, 204, 204));
        btnFood.setText("Comidas");
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });
        getContentPane().add(btnFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, -1, 38));

        btnDrink.setBackground(new java.awt.Color(51, 51, 51));
        btnDrink.setForeground(new java.awt.Color(204, 204, 204));
        btnDrink.setText("Bebidas");
        btnDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkActionPerformed(evt);
            }
        });
        getContentPane().add(btnDrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 46, -1, 38));

        btnCar.setBackground(new java.awt.Color(51, 51, 51));
        btnCar.setForeground(new java.awt.Color(204, 204, 204));
        btnCar.setText("Autos");
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 77, 41));

        btnTravel.setBackground(new java.awt.Color(51, 51, 51));
        btnTravel.setForeground(new java.awt.Color(204, 204, 204));
        btnTravel.setText("Viajes");
        btnTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelActionPerformed(evt);
            }
        });
        getContentPane().add(btnTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 120, -1, 41));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 190, 207, 10));

        list1.setBackground(new java.awt.Color(51, 51, 51));
        list1.setForeground(new java.awt.Color(204, 204, 204));
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, 90));

        lblTotal.setBackground(new java.awt.Color(51, 51, 51));
        lblTotal.setForeground(new java.awt.Color(204, 204, 204));
        lblTotal.setText("Total : 0");
        lblTotal.setOpaque(true);
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 265, -1, -1));

        lblCred.setBackground(new java.awt.Color(51, 51, 51));
        lblCred.setForeground(new java.awt.Color(204, 204, 204));
        lblCred.setText("Creditos : ");
        lblCred.setOpaque(true);
        getContentPane().add(lblCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setForeground(new java.awt.Color(204, 204, 204));
        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnBuy.setBackground(new java.awt.Color(51, 51, 51));
        btnBuy.setForeground(new java.awt.Color(204, 204, 204));
        btnBuy.setText("Comprar");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btnDelete.setBackground(new java.awt.Color(51, 51, 51));
        btnDelete.setForeground(new java.awt.Color(204, 204, 204));
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setForeground(new java.awt.Color(204, 204, 204));
        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        list2.setBackground(new java.awt.Color(51, 51, 51));
        list2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 260, 90));
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelActionPerformed
               list1.removeAll();
        list1.add("Cancun -Creditos: 200");
       list1.add("Rio do Janeiro-Creditos: 500");
       list1.add("Disney -Creditos: 1500");
       list1.add("Dubai -Creditos: 2000");
    }//GEN-LAST:event_btnTravelActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
       list1.removeAll();
       list1.add("Fiat 600 (Usado, un poco roto) -Creditos: 1000");
       list1.add("Ford Falcón -Creditos: 2000");
       list1.add("Ferrari -Creditos: 80000");
       list1.add("Lamborghini -Creditos: 125000");
    }//GEN-LAST:event_btnCarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         if (list2.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,"Seleccione algo para borrar");
            }else{
                String[] partes = list2.getSelectedItem().split(": ");
                int precio = Integer.parseInt(partes[1]);
                total -= precio;
                lblTotal.setText("Total : "+ total);
                list2.remove(list2.getSelectedItem());
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Program.vtnMenu.setVisible(true);
        Program.vtnTienda.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
       list1.removeAll();
        list1.add("5 Arepas cocinadas por Angel -Creditos: 5");
       list1.add("5 visitas al Burker King -Creditos: 10");
       list1.add("6 tablas de Sushi -Creditos: 25");
       list1.add("1 año de restaurante gratis-Creditos: 150");
       
    }//GEN-LAST:event_btnFoodActionPerformed

    private void btnDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkActionPerformed
       list1.removeAll();
        list1.add("1 pack de Coca Cola (x6) -Creditos: 5");
       list1.add("2 Champagnes -Creditos: 10");
       list1.add("1 pack Vodka Smirnoff (x4) -Creditos: 50");
       list1.add("1 Wisky Blue Label -Creditos: 200");
    }//GEN-LAST:event_btnDrinkActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         if (list1.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,"Seleccione algo para añadir");
            }else{
            list2.add(list1.getSelectedItem());
            String[] partes = list1.getSelectedItem().split(": ");
            int precio = Integer.parseInt(partes[1]);
            total += precio;
            lblTotal.setText("Total : "+ total);
         }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        if(Program.creditos < total) {
           JOptionPane.showMessageDialog(this, "Creditos Insuficientes");
        }
        else {
            if (total == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione algo para comprar");
            } else {
            Program.creditos -= total;
            total = total - total;
            lblTotal.setText("Total : "+ total);
            list2.removeAll();
            JOptionPane.showMessageDialog(this, "Has canjeado con exito. \n Retire el ticket al salir" );
            Program.actualizarLabelCreditos();
            }
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDrink;
    private javax.swing.JButton btnFood;
    private javax.swing.JButton btnTravel;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblCred;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTotal;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables
}
